---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.99.10 zabbix zabbix.dexter.com.br
        - 192.168.99.11 prometheus prometheus.dexter.com.br
        - 192.168.99.12 4flix 4flix.dexter.com.br
        - 192.168.99.13 graylog graylog.dexter.com.br
        
    - name: Configura hostname da VM
      hostname:
        name: prometheus

    - name: Instalando pacotes de dependencias para o curso
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - policycoreutils-python-utils
        - git
        - net-tools
        - tzdata
        - tzdata-java
        
    - name: Atualiza o timezone
      shell: timedatectl set-timezone America/Sao_Paulo
      args:
